## Introduction to Data Science

### Introduction to Numpy and Pandas

In [1]:
#import pylab
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

import os
import pathlib


%matplotlib inline
#%matplotlib notebook

## [Numpy Basics](https://www.datacamp.com/community/tutorials/python-numpy-tutorial)

What Is A Python Numpy Array?  

NumPy arrays are a bit like Python lists, but still very much different at the same time. For those of you who are new to the topic, let’s clarify what it exactly is and what it’s good for.   

As the name kind of gives away, a NumPy array is a central data structure of the numpy library. The library’s name is actually short for “Numeric Python” or “Numerical Python”.  

In other words, NumPy is a Python library that is the core library for scientific computing in Python. It contains a collection of tools and techniques that can be used to solve on a computer mathematical models of problems in Science and Engineering. One of these tools is a high-performance multidimensional array object that is a powerful data structure for efficient computation of arrays and matrices. To work with these arrays, there’s a huge amount of high-level mathematical functions operate on these matrices and arrays.  

Then, what is an array?  

When you look at the print of a couple arrays, you could see it as grid that contains values of the same type. The array holds and represents any regular data in a structured way.  

However, you should know that, on a structural level, an array is basically nothing but pointers. It’s a combination of a memory address, a data type, a shape and strides:  

The data pointer indicates the memory address of the first byte in the array,  
The data type or dtype pointer describes the kind of elements that are contained within the array,  
The shape indicates the shape of the array, and
The strides are the number of bytes that should be skipped in memory to go to the next element.   

If your strides are (10,1), you need to proceed one byte to get to the next column and 10 bytes to locate the next row.  

### Creating Arrays:

In [2]:
my_numbers = [1,2,3,4]
simple_array = np.array(my_numbers)
print(simple_array)

[1 2 3 4]


In [3]:
type(simple_array)

numpy.ndarray

In [4]:
simple_array + 34

array([35, 36, 37, 38])

In [5]:
simple_array.shape

(4,)

In [6]:
simple_array.dtype

dtype('int64')

In [8]:
simple_array.data

In [9]:
simple_array.strides

(8,)

In [10]:
my_other_numbers = [[1,2,3],[4,5,6],[7,8,9]]
other_simple_array = np.array(my_other_numbers)
other_simple_array

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [11]:
other_simple_array.shape

(3, 3)

In [12]:
#a = np.arange(20)
a = np.arange(1,5,0.2)
print(a)

[1.  1.2 1.4 1.6 1.8 2.  2.2 2.4 2.6 2.8 3.  3.2 3.4 3.6 3.8 4.  4.2 4.4
 4.6 4.8]


In [13]:
b = np.linspace(1,10,30)
#b = np.linspace(1,2*np.pi,50)
print(b)

[ 1.          1.31034483  1.62068966  1.93103448  2.24137931  2.55172414
  2.86206897  3.17241379  3.48275862  3.79310345  4.10344828  4.4137931
  4.72413793  5.03448276  5.34482759  5.65517241  5.96551724  6.27586207
  6.5862069   6.89655172  7.20689655  7.51724138  7.82758621  8.13793103
  8.44827586  8.75862069  9.06896552  9.37931034  9.68965517 10.        ]


In [14]:
b2 = np.logspace(1,100,30)
print(b2)

[1.00000000e+001 2.59294380e+004 6.72335754e+007 1.74332882e+011
 4.52035366e+014 1.17210230e+018 3.03919538e+021 7.88046282e+024
 2.04335972e+028 5.29831691e+031 1.37382380e+035 3.56224789e+038
 9.23670857e+041 2.39502662e+045 6.21016942e+048 1.61026203e+052
 4.17531894e+055 1.08263673e+059 2.80721620e+062 7.27895384e+065
 1.88739182e+069 4.89390092e+072 1.26896100e+076 3.29034456e+079
 8.53167852e+082 2.21221629e+086 5.73615251e+089 1.48735211e+093
 3.85662042e+096 1.00000000e+100]


In [15]:
a1 = np.zeros((3,4))
print(a1)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [16]:
a2 = np.ones((2,2))
print(a2)

[[1. 1.]
 [1. 1.]]


In [17]:
a3 = np.empty((2,3))
print(a3)

[[2.27152333e-316 5.39494389e-317 5.31021756e-317]
 [6.91499166e-310 2.27251383e-316 6.91507865e-310]]


In [18]:
a4 = np.identity(3)
print(a4)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [19]:
a5 = np.eye(2)        
print(a5)

[[1. 0.]
 [0. 1.]]


In [21]:
a6 = np.full((4,2), 7)
print(a6)

[[7 7]
 [7 7]
 [7 7]
 [7 7]]


In [22]:
a7 = np.random.random((2,2))  
print(a7)

[[0.49256566 0.25805908]
 [0.79181639 0.66411795]]


#### Modifying Dimensions:

In [23]:
c = np.arange(100)
print(c)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]


In [24]:
d = c.reshape(4,5,5)
print(d)

[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]
  [15 16 17 18 19]
  [20 21 22 23 24]]

 [[25 26 27 28 29]
  [30 31 32 33 34]
  [35 36 37 38 39]
  [40 41 42 43 44]
  [45 46 47 48 49]]

 [[50 51 52 53 54]
  [55 56 57 58 59]
  [60 61 62 63 64]
  [65 66 67 68 69]
  [70 71 72 73 74]]

 [[75 76 77 78 79]
  [80 81 82 83 84]
  [85 86 87 88 89]
  [90 91 92 93 94]
  [95 96 97 98 99]]]


In [26]:
d = np.random.random(100).reshape(4,25)
print(d)

[[0.14756392 0.39313065 0.0025445  0.90222453 0.23075315 0.92728418
  0.70700737 0.28532065 0.51746715 0.45209621 0.62558248 0.25610094
  0.52665833 0.94299071 0.20760618 0.19665872 0.83370729 0.04540372
  0.74640147 0.85165044 0.69117281 0.0632293  0.35273857 0.04150011
  0.03521859]
 [0.8738017  0.17480272 0.99044623 0.85830543 0.73547664 0.46823983
  0.86559322 0.98215088 0.43921938 0.26202556 0.69854774 0.18963416
  0.54131736 0.67312812 0.17353999 0.92083161 0.79161382 0.04651925
  0.96884502 0.42316454 0.70751912 0.51600922 0.51283243 0.53754893
  0.91463822]
 [0.59956668 0.77226307 0.64850472 0.25714129 0.67233403 0.00971545
  0.57292154 0.86971822 0.79840233 0.34012459 0.0040392  0.71075066
  0.07585854 0.74645847 0.14948683 0.32060765 0.16071228 0.81538412
  0.19815208 0.17148323 0.16303146 0.99774688 0.85384952 0.7629282
  0.66551627]
 [0.78017954 0.02088575 0.61571154 0.70755611 0.98710755 0.5225481
  0.18588252 0.71163942 0.59460962 0.70234217 0.44363576 0.61448914
  0.2770

In [27]:
print(c.shape)
print(d.shape)
print(np.ndim(d))
print(d.dtype.name)

(100,)
(4, 25)
2
float64


In [28]:
d2 = np.arange(100).reshape(2,10,5)
d2

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34],
        [35, 36, 37, 38, 39],
        [40, 41, 42, 43, 44],
        [45, 46, 47, 48, 49]],

       [[50, 51, 52, 53, 54],
        [55, 56, 57, 58, 59],
        [60, 61, 62, 63, 64],
        [65, 66, 67, 68, 69],
        [70, 71, 72, 73, 74],
        [75, 76, 77, 78, 79],
        [80, 81, 82, 83, 84],
        [85, 86, 87, 88, 89],
        [90, 91, 92, 93, 94],
        [95, 96, 97, 98, 99]]])

In [29]:
x = np.arange(12).reshape((3,4))
print(x)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [30]:
print(x.shape)

(3, 4)


In [35]:
x.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [36]:
# Resize `x` to ((6,4))
y = np.resize(x, (7,5))
print(x)
print()
print(y)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11  0  1  2]
 [ 3  4  5  6  7]
 [ 8  9 10 11  0]
 [ 1  2  3  4  5]
 [ 6  7  8  9 10]]


### Slicing multidimensional arrays

In [38]:
d = np.arange(40).reshape(4,2,5)
print(d)

[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]]

 [[10 11 12 13 14]
  [15 16 17 18 19]]

 [[20 21 22 23 24]
  [25 26 27 28 29]]

 [[30 31 32 33 34]
  [35 36 37 38 39]]]


In [44]:
d[1,:,3:]

array([[13, 14],
       [18, 19]])

In [45]:
d.shape

(4, 2, 5)

In [46]:
d[d%2==0]

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34, 36, 38])

In [47]:
d[~d%2==0]  #negation of condition

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33,
       35, 37, 39])

In [48]:
# Create a new array from which we will select elements
a = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
print(a)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [50]:
# Create an array of indices
b = np.array([0, 2, 0, 1])
print(b)

[0 2 0 1]


In [51]:
# Select one element from each row of a using the indices in b
print(a[np.arange(4), b])

[ 1  6  7 11]


In [52]:
# Mutate one element from each row of a using the indices in b
a[np.arange(4), b] += 10
print(a)

[[11  2  3]
 [ 4  5 16]
 [17  8  9]
 [10 21 12]]


In [53]:
d

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9]],

       [[10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]],

       [[20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29]],

       [[30, 31, 32, 33, 34],
        [35, 36, 37, 38, 39]]])

In [56]:
# Boolean array indexing
bool_idx = (d > 13)
print(bool_idx)

[[[False False False False False]
  [False False False False False]]

 [[False False False False  True]
  [ True  True  True  True  True]]

 [[ True  True  True  True  True]
  [ True  True  True  True  True]]

 [[ True  True  True  True  True]
  [ True  True  True  True  True]]]


In [57]:
print(d[bool_idx])

[14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37
 38 39]


### datatypes

In [58]:
x = np.array([1, 2])   # Let numpy choose the datatype
print(x.dtype)         # Prints "int64"

int64


In [59]:
x = np.array([1.0, 2.0])   # Let numpy choose the datatype
print(x.dtype)             # Prints "float64"

float64


In [62]:
x = np.array([1, 2], dtype=np.float64)   # Force a particular datatype
print(x.dtype)                         # Prints "int64"

float64


### Inline and vectorized operations:

In [63]:
a

array([[11,  2,  3],
       [ 4,  5, 16],
       [17,  8,  9],
       [10, 21, 12]])

In [64]:
a * 2

array([[22,  4,  6],
       [ 8, 10, 32],
       [34, 16, 18],
       [20, 42, 24]])

In [65]:
# the original array stays the same
a

array([[11,  2,  3],
       [ 4,  5, 16],
       [17,  8,  9],
       [10, 21, 12]])

In [66]:
a.cumsum()

array([ 11,  13,  16,  20,  25,  41,  58,  66,  75,  85, 106, 118])

In [45]:
a = np.arange(16).reshape(4,4)
np.vstack([a,np.arange(4).reshape(1,4)])

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [ 0,  1,  2,  3]])

In [68]:
np.hstack([a,np.arange(4).reshape(4,1)])

array([[11,  2,  3,  0],
       [ 4,  5, 16,  1],
       [17,  8,  9,  2],
       [10, 21, 12,  3]])

### Array Math

In [69]:
x = np.array([[1,2],[3,4]], dtype=np.float64)
y = np.array([[5,6],[7,8]], dtype=np.float64)

# Elementwise sum; both produce the array
# [[ 6.0  8.0]
#  [10.0 12.0]]
print(x + y)
print(np.add(x, y))

[[ 6.  8.]
 [10. 12.]]
[[ 6.  8.]
 [10. 12.]]


In [70]:
# Elementwise difference; both produce the array
# [[-4.0 -4.0]
#  [-4.0 -4.0]]
print(x - y)
print(np.subtract(x, y))

[[-4. -4.]
 [-4. -4.]]
[[-4. -4.]
 [-4. -4.]]


In [71]:
# Elementwise product; both produce the array
# [[ 5.0 12.0]
#  [21.0 32.0]]
print(x * y)
print(np.multiply(x, y))

[[ 5. 12.]
 [21. 32.]]
[[ 5. 12.]
 [21. 32.]]


In [72]:
# Elementwise division; both produce the array
# [[ 0.2         0.33333333]
#  [ 0.42857143  0.5       ]]
print(x / y)
print(np.divide(x, y))

[[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]


In [73]:
# Elementwise square root; produces the array
# [[ 1.          1.41421356]
#  [ 1.73205081  2.        ]]
print(np.sqrt(x))

[[1.         1.41421356]
 [1.73205081 2.        ]]


In [74]:
x = np.array([[1,2],[3,4]])
y = np.array([[5,6],[7,8]])
v = np.array([9,10])
w = np.array([11, 12])

In [75]:
print(x)
print()
print(y)
print()
print(v)
print()
print(w)

[[1 2]
 [3 4]]

[[5 6]
 [7 8]]

[ 9 10]

[11 12]


In [76]:
# Inner product of vectors; both produce 219
print(v.dot(w))
print(np.dot(v, w))

219
219


In [77]:
# Matrix / vector product; both produce the rank 1 array [29 67]
print(x.dot(v))
print(np.dot(x, v))

[29 67]
[29 67]


In [78]:
# Matrix / matrix product; both produce the rank 2 array
print(x.dot(y))
print(np.dot(x, y))

[[19 22]
 [43 50]]
[[19 22]
 [43 50]]


In [80]:
x = np.array([[1,2],[3,4]])
print(x)
print(np.sum(x))  # Compute sum of all elements; prints "10"
print(np.sum(x, axis=0))  # Compute sum of each column; prints "[4 6]"
print(np.sum(x, axis=1))  # Compute sum of each row; prints "[3 7]"

[[1 2]
 [3 4]]
10
[4 6]
[3 7]


In [81]:
x = np.array([[1,2], [3,4]])

In [82]:
print(x)
print()
print(x.T)

[[1 2]
 [3 4]]

[[1 3]
 [2 4]]


In [83]:
# Note that taking the transpose of a rank 1 array does nothing:
v = np.array([1,2,3])

In [84]:
print(v)
print()
print(v.T)

[1 2 3]

[1 2 3]


In [85]:
# We will add the vector v to each row of the matrix x,
# storing the result in the matrix y
x = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
v = np.array([1, 0, 1])
y = np.empty_like(x)   # Create an empty matrix with the same shape as x

In [86]:
print(x)
print()
print(v)
print()
print(y)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]

[1 0 1]

[[    139962750077912     139962750077912 3184080310729648249]
 [4404653520118952224 8390326387129478688 8658281795624394617]
 [8233459878998319145 2336912048420839781 7020303100157128037]
 [8388366762297094772 7021991863916961896 7309449296458311021]]


In [87]:
for i in range(4):
    y[i, :] = x[i, :] + v
print(y)

[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]


This works; however when the matrix x is very large, computing an explicit loop in Python could be slow. Note that adding the vector v to each row of the matrix x is equivalent to forming a matrix vv by stacking multiple copies of v vertically, then performing elementwise summation of x and vv. We could implement this approach like this:

In [88]:
# We will add the vector v to each row of the matrix x,
# storing the result in the matrix y
x = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
v = np.array([1, 0, 1])
vv = np.tile(v, (4, 1))   # Stack 4 copies of v on top of each other
print(vv)

[[1 0 1]
 [1 0 1]
 [1 0 1]
 [1 0 1]]


In [89]:
y = x + vv  # Add x and vv elementwise
print(y)

[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]


Numpy broadcasting allows us to perform this computation without actually creating multiple copies of v. Consider this version, using broadcasting:

In [90]:
x = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
v = np.array([1, 0, 1])
y = x + v  # Add v to each row of x using broadcasting
print(y)

[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]


The line y = x + v works even though x has shape (4, 3) and v has shape (3,) due to broadcasting; this line works as if v actually had shape (4, 3), where each row was a copy of v, and the sum was performed elementwise.

In [91]:
# Initialize `x` and `y`
x = np.ones((3,4))
y = np.random.random((5,1,4))

# Add `x` and `y`
print(x + y)

[[[1.07032573 1.68035318 1.01381298 1.60126178]
  [1.07032573 1.68035318 1.01381298 1.60126178]
  [1.07032573 1.68035318 1.01381298 1.60126178]]

 [[1.31196829 1.94523605 1.06342201 1.79751301]
  [1.31196829 1.94523605 1.06342201 1.79751301]
  [1.31196829 1.94523605 1.06342201 1.79751301]]

 [[1.21636762 1.24535716 1.23326316 1.20602932]
  [1.21636762 1.24535716 1.23326316 1.20602932]
  [1.21636762 1.24535716 1.23326316 1.20602932]]

 [[1.68562817 1.2265503  1.02100707 1.35139622]
  [1.68562817 1.2265503  1.02100707 1.35139622]
  [1.68562817 1.2265503  1.02100707 1.35139622]]

 [[1.17830036 1.45120789 1.01008625 1.89074391]
  [1.17830036 1.45120789 1.01008625 1.89074391]
  [1.17830036 1.45120789 1.01008625 1.89074391]]]


You see that, even though x and y seem to have somewhat different dimensions, the two can be added together.  
That is because they are compatible in all dimensions:

    Array x has dimensions 3 X 4,
    Array y has dimensions 5 X 1 X 4

Since you have seen above that dimensions are also compatible if one of them is equal to 1, you see that these two arrays are indeed a good candidate for broadcasting!  

What you will notice is that in the dimension where y has size 1 and the other array has a size greater than 1 (that is, 3), the first array behaves as if it were copied along that dimension.  

Note that the shape of the resulting array will again be the maximum size along each dimension of x and y: the dimension of the result will be (5,3,4)  

In short, if you want to make use of broadcasting, you will rely a lot on the shape and dimensions of the arrays with which you’re working.  

# Pandas

### Pandas Data Structures: Series

In [102]:
obj = pd.Series([4, 7, -5, 3, 5])
obj

0    4
1    7
2   -5
3    3
4    5
dtype: int64

In [105]:
obj.values

array([ 4,  7, -5,  3,  5])

In [107]:
obj.index

RangeIndex(start=0, stop=5, step=1)

In [108]:
obj.index = ['Bob', 'Steve', 'Jeff', 'Ryan', 'Fernie']
obj

Bob       4
Steve     7
Jeff     -5
Ryan      3
Fernie    5
dtype: int64

In [110]:
obj['Bob']

4

In [111]:
obj2 = pd.Series([4, 7, -5, 3], index=['d', 'b', 'a', 'c'])
obj2

d    4
b    7
a   -5
c    3
dtype: int64

In [112]:
obj2['c']

3

In [113]:
obj2[['c', 'a', 'd']]

c    3
a   -5
d    4
dtype: int64

In [114]:
obj2[obj2 < 0]

a   -5
dtype: int64

In [115]:
obj2 * 2

d     8
b    14
a   -10
c     6
dtype: int64

In [116]:
np.exp(obj2)

d      54.598150
b    1096.633158
a       0.006738
c      20.085537
dtype: float64

In [117]:
sdata = {'Ohio': 35000, 'Texas': 71000, 'Oregon': 16000, 'Utah': 5000}
obj3 = pd.Series(sdata)
obj3

Ohio      35000
Oregon    16000
Texas     71000
Utah       5000
dtype: int64

In [118]:
states = ['California', 'Ohio', 'Oregon', 'Texas']
obj4 = pd.Series(sdata, index=states)
obj4

California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
dtype: float64

In [119]:
pd.isnull(obj4)

California     True
Ohio          False
Oregon        False
Texas         False
dtype: bool

In [120]:
pd.notnull(obj4)

California    False
Ohio           True
Oregon         True
Texas          True
dtype: bool

In [121]:
obj3 + obj4

California         NaN
Ohio           70000.0
Oregon         32000.0
Texas         142000.0
Utah               NaN
dtype: float64

In [123]:
obj4.name = 'population'
obj4.index.name = 'state'
obj4

state
California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
Name: population, dtype: float64

### Pandas Data Structures: Dataframe

In [124]:
data = {'state': ['Ohio', 'Ohio', 'Ohio', 'Nevada', 'Nevada'],'year': [2000, 2001, 2002, 2001, 2002],'pop': [1.5, 1.7, 3.6, 2.4, 2.9]}
frame = pd.DataFrame(data)
frame

pop   state  year
0  1.5    Ohio  2000
1  1.7    Ohio  2001
2  3.6    Ohio  2002
3  2.4  Nevada  2001
4  2.9  Nevada  2002

In [130]:
frame['pop']

0    1.5
1    1.7
2    3.6
3    2.4
4    2.9
Name: pop, dtype: float64

In [131]:
pd.DataFrame(data, columns=['year', 'state', 'pop'])

year   state  pop
0  2000    Ohio  1.5
1  2001    Ohio  1.7
2  2002    Ohio  3.6
3  2001  Nevada  2.4
4  2002  Nevada  2.9

In [132]:
frame2 = pd.DataFrame(data, columns=['year', 'state', 'pop', 'debt'],index=['one', 'two', 'three', 'four', 'five'])
frame2

year   state  pop debt
one    2000    Ohio  1.5  NaN
two    2001    Ohio  1.7  NaN
three  2002    Ohio  3.6  NaN
four   2001  Nevada  2.4  NaN
five   2002  Nevada  2.9  NaN

In [133]:
frame2['nova'] = 13
frame2

year   state  pop debt  nova
one    2000    Ohio  1.5  NaN    13
two    2001    Ohio  1.7  NaN    13
three  2002    Ohio  3.6  NaN    13
four   2001  Nevada  2.4  NaN    13
five   2002  Nevada  2.9  NaN    13

In [134]:
frame2.nova = 23
frame2

year   state  pop debt  nova
one    2000    Ohio  1.5  NaN    23
two    2001    Ohio  1.7  NaN    23
three  2002    Ohio  3.6  NaN    23
four   2001  Nevada  2.4  NaN    23
five   2002  Nevada  2.9  NaN    23

In [135]:
frame2.columns

Index(['year', 'state', 'pop', 'debt', 'nova'], dtype='object')

In [136]:
frame2['state']

one        Ohio
two        Ohio
three      Ohio
four     Nevada
five     Nevada
Name: state, dtype: object

In [137]:
frame2.state

one        Ohio
two        Ohio
three      Ohio
four     Nevada
five     Nevada
Name: state, dtype: object

In [138]:
#frame2.loc['three']
frame2.loc['three','state']

'Ohio'

In [139]:
frame2['debt'] = 16.5
frame2

year   state  pop  debt  nova
one    2000    Ohio  1.5  16.5    23
two    2001    Ohio  1.7  16.5    23
three  2002    Ohio  3.6  16.5    23
four   2001  Nevada  2.4  16.5    23
five   2002  Nevada  2.9  16.5    23

In [140]:
frame2['debt'] = np.arange(5.)
frame2

year   state  pop  debt  nova
one    2000    Ohio  1.5   0.0    23
two    2001    Ohio  1.7   1.0    23
three  2002    Ohio  3.6   2.0    23
four   2001  Nevada  2.4   3.0    23
five   2002  Nevada  2.9   4.0    23

In [141]:
val = pd.Series([-1.2, -1.5, -1.7], index=['two', 'four', 'five'])
frame2['debt'] = val
frame2

year   state  pop  debt  nova
one    2000    Ohio  1.5   NaN    23
two    2001    Ohio  1.7  -1.2    23
three  2002    Ohio  3.6   NaN    23
four   2001  Nevada  2.4  -1.5    23
five   2002  Nevada  2.9  -1.7    23

In [142]:
frame2['eastern'] = frame2.state == 'Ohio'
frame2

year   state  pop  debt  nova  eastern
one    2000    Ohio  1.5   NaN    23     True
two    2001    Ohio  1.7  -1.2    23     True
three  2002    Ohio  3.6   NaN    23     True
four   2001  Nevada  2.4  -1.5    23    False
five   2002  Nevada  2.9  -1.7    23    False

In [143]:
del frame2['eastern']
frame2.columns

Index(['year', 'state', 'pop', 'debt', 'nova'], dtype='object')

In [144]:
transpose = frame2.pivot(index= 'year', columns='state', values='pop') 
transpose

state  Nevada  Ohio
year               
2000      NaN   1.5
2001      2.4   1.7
2002      2.9   3.6

In [145]:
pop = {'Nevada': {2001: 2.4, 2002: 2.9},'Ohio': {2000: 1.5, 2001: 1.7, 2002: 3.6}}
frame3 = pd.DataFrame(pop)
frame3

Nevada  Ohio
2000     NaN   1.5
2001     2.4   1.7
2002     2.9   3.6

In [146]:
frame3.T

2000  2001  2002
Nevada   NaN   2.4   2.9
Ohio     1.5   1.7   3.6

In [147]:
pd.DataFrame(pop, index=[2001, 2002, 2003])

Nevada  Ohio
2001     2.4   1.7
2002     2.9   3.6
2003     NaN   NaN

In [148]:
pdata = {'Ohio': frame3['Ohio'][:-1],'Nevada': frame3['Nevada'][:2]}
pd.DataFrame(pdata)

Nevada  Ohio
2000     NaN   1.5
2001     2.4   1.7

In [149]:
frame3.index.name = 'year'; frame3.columns.name = 'state'
frame3

state  Nevada  Ohio
year               
2000      NaN   1.5
2001      2.4   1.7
2002      2.9   3.6

In [150]:
pop = {'Nevada': {2001: 2.4, 2002: 2.9},'Ohio': {2000: 1.5, 2001: 1.7, 2002: 3.6}}
frame4 = pd.DataFrame(pop)
frame4

Nevada  Ohio
2000     NaN   1.5
2001     2.4   1.7
2002     2.9   3.6

In [151]:
frame4.loc[2000,'Nevada'] = 2
frame4

Nevada  Ohio
2000     2.0   1.5
2001     2.4   1.7
2002     2.9   3.6

In [152]:
frame5 = pd.concat([frame4, frame4])
frame5

Nevada  Ohio
2000     2.0   1.5
2001     2.4   1.7
2002     2.9   3.6
2000     2.0   1.5
2001     2.4   1.7
2002     2.9   3.6

In [108]:
frame5.drop_duplicates(['Nevada'])

Nevada  Ohio
2000     2.0   1.5
2001     2.4   1.7
2002     2.9   3.6

In [109]:
dates = pd.date_range("20160101", periods=10)
data = np.random.random((10,3))
column_names = ['Column1', 'Column2', 'Column3']
df = pd.DataFrame(data, index=dates, columns=column_names)
df.head(10)

Column1   Column2   Column3
2016-01-01  0.240841  0.522289  0.722822
2016-01-02  0.969244  0.228260  0.487049
2016-01-03  0.356126  0.321509  0.195831
2016-01-04  0.403184  0.546886  0.077243
2016-01-05  0.794290  0.004394  0.896263
2016-01-06  0.028639  0.837349  0.760233
2016-01-07  0.667131  0.258288  0.683920
2016-01-08  0.326585  0.410338  0.984604
2016-01-09  0.257363  0.201014  0.969749
2016-01-10  0.460921  0.668459  0.549353

In [110]:
df[1:3]

Column1   Column2   Column3
2016-01-02  0.969244  0.228260  0.487049
2016-01-03  0.356126  0.321509  0.195831

In [111]:
df['20160104':'20160107']

Column1   Column2   Column3
2016-01-04  0.403184  0.546886  0.077243
2016-01-05  0.794290  0.004394  0.896263
2016-01-06  0.028639  0.837349  0.760233
2016-01-07  0.667131  0.258288  0.683920

In [112]:
df.loc['20160101':'20160102',['Column1','Column3']]

Column1   Column3
2016-01-01  0.240841  0.722822
2016-01-02  0.969244  0.487049

In [113]:
df.iloc[3:5, 0:2]

Column1   Column2
2016-01-04  0.403184  0.546886
2016-01-05  0.794290  0.004394

In [114]:
df.describe()

Column1    Column2    Column3
count  10.000000  10.000000  10.000000
mean    0.450432   0.399879   0.632707
std     0.282853   0.247615   0.309383
min     0.028639   0.004394   0.077243
25%     0.274668   0.235767   0.502625
50%     0.379655   0.365923   0.703371
75%     0.615579   0.540737   0.862256
max     0.969244   0.837349   0.984604

In [115]:
df.sort_index(axis=0, ascending=False,) # inplace=True)

Column1   Column2   Column3
2016-01-10  0.460921  0.668459  0.549353
2016-01-09  0.257363  0.201014  0.969749
2016-01-08  0.326585  0.410338  0.984604
2016-01-07  0.667131  0.258288  0.683920
2016-01-06  0.028639  0.837349  0.760233
2016-01-05  0.794290  0.004394  0.896263
2016-01-04  0.403184  0.546886  0.077243
2016-01-03  0.356126  0.321509  0.195831
2016-01-02  0.969244  0.228260  0.487049
2016-01-01  0.240841  0.522289  0.722822

In [116]:
df.sort_values(by='Column2')

Column1   Column2   Column3
2016-01-05  0.794290  0.004394  0.896263
2016-01-09  0.257363  0.201014  0.969749
2016-01-02  0.969244  0.228260  0.487049
2016-01-07  0.667131  0.258288  0.683920
2016-01-03  0.356126  0.321509  0.195831
2016-01-08  0.326585  0.410338  0.984604
2016-01-01  0.240841  0.522289  0.722822
2016-01-04  0.403184  0.546886  0.077243
2016-01-10  0.460921  0.668459  0.549353
2016-01-06  0.028639  0.837349  0.760233

In [117]:
dates1 = pd.date_range("20160101", periods=6)
data1 = np.random.random((6,2))
column_names1 = ['ColumnA', 'ColumnB']

dates2 = pd.date_range("20160101", periods=7)
data2 = np.random.random((7,2))
column_names2 = ['ColumnC', 'ColumnD']

df1 = pd.DataFrame(data1, index=dates1, columns=column_names1)
df2 = pd.DataFrame(data2, index=dates2, columns=column_names2)

In [118]:
df1.head()

ColumnA   ColumnB
2016-01-01  0.041699  0.222940
2016-01-02  0.603418  0.703103
2016-01-03  0.246290  0.686958
2016-01-04  0.935233  0.991302
2016-01-05  0.189316  0.579263

In [119]:
df2.head()

ColumnC   ColumnD
2016-01-01  0.232406  0.268335
2016-01-02  0.907167  0.346246
2016-01-03  0.472135  0.433341
2016-01-04  0.661549  0.458543
2016-01-05  0.630919  0.600120

In [120]:
df1.join(df2)

ColumnA   ColumnB   ColumnC   ColumnD
2016-01-01  0.041699  0.222940  0.232406  0.268335
2016-01-02  0.603418  0.703103  0.907167  0.346246
2016-01-03  0.246290  0.686958  0.472135  0.433341
2016-01-04  0.935233  0.991302  0.661549  0.458543
2016-01-05  0.189316  0.579263  0.630919  0.600120
2016-01-06  0.394867  0.322051  0.165572  0.650530

In [121]:
df3 = df1.join(df2)

# add a column to df to group on
df3['ProfitLoss'] = pd.Series(['Profit', 
                               'Loss', 
                               'Profit', 
                               'Profit', 
                               'Profit', 
                               'Loss', 
                               'Profit', 
                               'Profit', 
                               'Profit', 
                               'Loss'], index=dates)

In [122]:
df3.head()

ColumnA   ColumnB   ColumnC   ColumnD ProfitLoss
2016-01-01  0.041699  0.222940  0.232406  0.268335     Profit
2016-01-02  0.603418  0.703103  0.907167  0.346246       Loss
2016-01-03  0.246290  0.686958  0.472135  0.433341     Profit
2016-01-04  0.935233  0.991302  0.661549  0.458543     Profit
2016-01-05  0.189316  0.579263  0.630919  0.600120     Profit

In [123]:
df3.groupby('ProfitLoss').mean()

ColumnA   ColumnB   ColumnC   ColumnD
ProfitLoss                                        
Loss        0.499143  0.512577  0.536369  0.498388
Profit      0.353134  0.620116  0.499252  0.440085